LOGGING:
  loggers:
    :
    handlers: [nts, h2]
  handlers:
    nts:
      class : logging.StreamHandler
      # formatter: brief
      level   : DEBUG
      filters: [plugin_name]
      stream  : ext://sys.stdout
    file:
      class : logging.handlers.RotatingFileHandler
      formatter: precise
      filename: logconfig.log
      maxBytes: 1024
      backupCount: 3