name: Regression Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  chemical-interactions-unittests:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: public.ecr.aws/h7r1e4h2/chemical-interactions:latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Latest chemical-interactions image
        run: |
          docker pull ${{ env.IMAGE_URI }}
      - name: Run chemical-interactions tests with newest lib
        run: |
          docker run --rm \
          -v $(pwd)/nanome:/opt/conda/lib/python3.7/site-packages/nanome \
          ${{ env.IMAGE_URI }} \
          python run_tests.py

  docking-smina-unittests:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: public.ecr.aws/h7r1e4h2/docking-smina:latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Latest docking-smina image
        run: |
          docker pull ${{ env.IMAGE_URI }}
      - name: Run docking-smina tests with newest lib
        run: |
          docker run --rm \
          -v $(pwd)/nanome:/opt/conda/lib/python3.7/site-packages/nanome \
          ${{ env.IMAGE_URI }} \
          python -m unittest discover tests.smina

  antibodies-unittests:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: public.ecr.aws/h7r1e4h2/antibodies:latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Latest image
        run: |
          docker pull ${{ env.IMAGE_URI }}
      - name: Run antibodies tests with newest lib
        run: |
          docker run --rm \
          -v $(pwd)/nanome:/opt/conda/lib/python3.7/site-packages/nanome \
          ${{ env.IMAGE_URI }} \
          python -m unittest discover tests
  
  esp-unittests:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: public.ecr.aws/h7r1e4h2/esp:latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Latest image
        run: |
          docker pull ${{ env.IMAGE_URI }}
      - name: Run tests with newest lib
        run: |
          docker run --rm \
          -v $(pwd)/nanome:/opt/conda/lib/python3.7/site-packages/nanome \
          ${{ env.IMAGE_URI }} \
          python -m unittest discover tests
  
  structure-prep-unittests:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: public.ecr.aws/h7r1e4h2/structure-prep:latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Latest image
        run: |
          docker pull ${{ env.IMAGE_URI }}
      - name: Run tests with newest lib
        run: |
          docker run --rm \
          -v $(pwd)/nanome:/opt/conda/lib/python3.7/site-packages/nanome \
          ${{ env.IMAGE_URI }} \
          python -m unittest discover tests
